### ISSUE TITLE
请问你们的标注工具是什么？能够分享一下吗？

### ISSUE THREAD

**Issue by Heart-beatsss** [xuuuluuu/SemEval_Triplet_data#5]
如题

**Comment by xuuuluuu** [comment]
请参考我们acknowledgement 以及paper原文对数据的描述，

Our datasets originate from SemEval Challenges ([Pontiki 2014](https://aclanthology.org/S14-2004/); [2015](https://doi.org/10.18653/v1/S15-2082); [2016](https://aclanthology.org/S16-1002/)). The annotation (opinion label) is derived from ([Fan et al. 2019](https://aclanthology.org/N19-1259/)), where they already annotated opinion terms.

我们没有对数据进行二次标注。

**Comment by Heart-beatsss** [comment]
好的，非常感谢
